### ISSUE TITLE
unable to stake from metamask mobile browser

### ISSUE THREAD

**Issue by Andrew-Pohl** [fuseio/staking-dapp#1]
Have had a few people message me on telegram about issues they are having with metamask using the mobile browser. Since Metamask app doesn't allow to change to landscape the stake/unstake pane is displayed off the screen.

Is it possible to make the page scrollable horizontally? 
![image](https://user-images.githubusercontent.com/55916961/103179342-e9c6cb80-4882-11eb-9486-9e8bfdb7b04f.png)

**Comment by LiorAgnin** [comment]
@Andrew-Pohl I fixed that,
Thanks

**Comment by Andrew-Pohl** [comment]
@LiorAgnin Awesome thanks Lior 👍
